### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [Kass-i/dots-and-boxes#1]
Hi. I am starting to learn C programming with Raylib and found your project while looking for easy simplified examples to learn from. Would you consider adding a permissive license to your project, to allow learning from the code you created, so I (and others) can maybe use similar algorithms to yours in our projects?

**Comment by Kass-i** [comment]
Hi, the license has just been added :)

**Comment by LifeCANvs** [comment]
> Hi, the license has just been added :)

Thank you so much for adding the MIT license, allowing anyone to learn from your work, and build upon it! Your game really looks nice :)
